### ISSUE TITLE
Write contributing section on README.md

### ISSUE THREAD

**Issue by LTKills** [LTKills/heroes-build-scrapper#18]
We've had some problems with contributors tackling issues without waiting to be assigned to them. I believe the contributing section should have 
* Instructions on how to correctly get an issue
* What to put in PRs (make an individual pull request for each suggestion)
* How to name PRs (the pull request and commit should have a useful title)
* Check your spelling and grammar.
* Add your nick to `PLAYERS.md`

**Comment by theIsaacLim** [comment]
[Here, I've done it](https://github.com/LTKills/heroes-build-scrapper/pull/26)
