### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by LTKills** [LTKills/heroes-build-scrapper#5]
Pep8, refactor code into more modularized version, etc.

**Comment by Nikoleta-v3** [comment]
Hey @LTKills! I really like your project. As a person that plays hots and always looks online for the builds this is a great tool. 

I am happy to help make the project easier to use. I am going to open some issues, feel free to disagree or even close them. 

The way I imagine refactoring project is in two files. One with the tools you are using and the main you are calling. So I would use the code as:

```
>>> import heroes_builds
>>> heroes_builds.update_all_heroes()
>>> heroes_builds.show('etc')
```
with a nice print message that lists the builds etc.

I am happy to help you to actually make a package  but if you want to keep it as just python files that is fine as well. 

Let me know what you think :smile:

**Comment by LTKills** [comment]
Seems great! I don't really know [how to make it into a real python package](https://stackoverflow.com/questions/9360458/creating-a-simple-package-that-can-be-install-via-pip-virtualenv#9360775) that you can actually `pip install` but I believe is definetly a great idea. 

One thing to keep in mind though is that when someone imports the package through pip there should be a path set for data files (just like /data/)

Obs1.: btw add me on hots (LTKills#1331) :smile: 

Obs2.: While writing obs1 I had the idea of having a contributors.md file where all the contributors can put their names/github nicks/bnet nicks

**Comment by Nikoleta-v3** [comment]
The path is an easy fix. One of the function will just take a string as an argument which will correspond to the path. 

However I was thinking of just creating a `setup.py` file. So If I wanted to use the project I would clone and then do `python setup.py` locally to install the package. 

I have experience with both approaches so up to you!

**Comment by LTKills** [comment]
I think a solution that kind of merges both approaches is to create a `setup.py` that takes an optional argument: the path. If the argument is not passed then we just create `/data` and `/data/buids` on the current directory.

**Comment by Nikoleta-v3** [comment]
Cool I am having a good at this now. I will open an `PR` soon and we can take it from there?

**Comment by LTKills** [comment]
Sounds good
